permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author:
  name: ckd
  email: chenkaidaa@163.com
  link: https://katechan.github.io
  weibo: http://weibo.com/
  github: https://github.com/katechan
  music: http://douban.fm/
  linkedin: https://cn.linkedin.com/

# 站点信息
title: ckd's Blog
description: My personal blog
url: https://katechan.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/Me.png
favicon: /public/img/Me.png

# google analytics 设置
ga:
  id: UA-66520108-1
  url: katechan.github.io

# disqus 设置
disqus:
  shortname: katechan

# 站内搜索:
# 微搜索:/pages/search.html

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates:
  - Optimization
  - Git

# qiniu CDN
# safe: false
# cdn_url : https://dn-yeungben.qbox.me

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  search: 搜索
